- hosts: generic
  become: true
  vars:
    oh_my_zsh_repo: https://github.com/robbyrussell/oh-my-zsh
    #ansible_python_interpreter: /usr/bin/python3
    ohmyzsh_install_dir: '/usr/local/share/ohmyzsh'
    root_home_dir: '/root'
    home_dir: '/home/'
    users:
      - admin
      - ansible
  handlers:
    - include: handlers/handler.yml

  tasks:
    - include: tasks/system_settings.yml
    - include: tasks/ntp.yml
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/dotfiles.yml
    - include: tasks/ohmyzsh.yml
    - include: tasks/ssh_config.yml
    - include: tasks/disable_login_banner.yml
    - include: tasks/cron.yml
    - include: tasks/install_iocage.yml
    - include: tasks/firewall.yml
    - include: tasks/fail2ban.yml
    - include: tasks/nginx.yml

- hosts: mail_servers
  become: true
  vars:
    domain: muessig.family

  handlers:
    - include: handlers/handler.yml
  
  tasks:
    # - include: tasks/postfix.yml