- name: enabling netdata
  lineinfile:
    path: /etc/rc.conf
    regex: '^netdata_enable'
    line: 'netdata_enable="YES"'

- name: run on socket
  lineinfile:
    path: /usr/local/etc/netdata/netdata.conf
    regex: '^\tbind to'
    line: ' bind to = unix:/var/run/netdata/netdata.sock'