- name: deploy oh-my-zsh
  git: 
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ ohmyzsh_install_dir }}"

# - name: get k plugin
#   git:
#     repo: "https://github.com/supercrabtree/k"
#     dest: "~/.oh-my-zsh/custom/plugins/k"  

# - name: download theme
#   get_url:
#     url: "http://raw.github.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme"
#     dest: "~/.oh-my-zsh/custom/themes/"

- name: theme install
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ ohmyzsh_install_dir }}/custom/themes/powerlevel10k"
    depth: 1

# plugins
- name: zsh-syntax-highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ohmyzsh_install_dir }}/custom/plugins/zsh-syntax-highlighting"

- name: zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ohmyzsh_install_dir }}/custom/plugins/zsh-autosuggestions"

# on freebsd you need to install lsd via rust and cargo
# see https://github.com/Peltoche/lsd


- name: templating ~/.zshrc
  template:
    src: "/usr/local/src/git/.dotfiles/.zshrc_bsd.j2"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.zshrc"
    backup: yes 
  with_items: "{{ users }}"

- name: templating ~/.theme.zsh
  template:
    src: "/usr/local/src/git/.dotfiles/.theme.zsh"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.theme.zsh"
    backup: yes
  with_items: "{{ users }}"

- name: set zsh as root default shell
  user: 
    name: root
    shell: /usr/local/bin/zsh