- name: templating root .ssh/authorized_keys
  template:
    src: "/usr/local/src/git/.dotfiles/.ssh/authorized_keys"
    dest: "~/.ssh/authorized_keys"
    backup: yes
  notify: restart ssh

- name: disable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart ssh