- name: Install ohmytmux
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.tmux/"
  with_items: "{{ users }}"

- name: Install tmux plugin manager
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.tmux/plugins/tpm"
  with_items: "{{ users }}"

- name: templating tmux base configuration
  file:
    src: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.tmux/.tmux.conf"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.tmux.conf"
    state: link
  with_items: "{{ users }}"

- name: templating tmux local configuration
  template:
    src: "/usr/local/src/git/.dotfiles/.tmux.conf.local.j2"
    dest: "{{ root_home_dir if item == 'root' else home_dir ~ item }}/.tmux.conf.local"
  with_items: "{{ users }}"